import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';
function setup(){const elements=new Map(),events={},windowEvents={},frames=new Map();let next=0;
 const make=id=>({id,style:{},textContent:'',innerHTML:'',disabled:false,classList:{values:new Set(),add(v){this.values.add(v)},remove(v){this.values.delete(v)},toggle(v,force){if(force??!this.values.has(v))this.values.add(v);else this.values.delete(v);return this.values.has(v)}},addEventListener(){},querySelectorAll(){return []},appendChild(){},focus(){},getContext(){return new Proxy({},{get:()=>()=>{}})}});
 const html=fs.readFileSync('play.html','utf8');for(const match of html.matchAll(/\bid="([^"]+)"/g)){assert(!elements.has(match[1]),'Duplicate HTML id '+match[1]);elements.set(match[1],make(match[1]));}
 const doc={hidden:false,getElementById(id){return elements.get(id)||null},createElement(){return make('')},addEventListener(k,v){events[k]=v}};
 const c={console,document:doc,window:{addEventListener(k,v){windowEvents[k]=v},innerWidth:390,innerHeight:844},performance:{now:()=>1000},requestAnimationFrame(f){frames.set(++next,f);return next},cancelAnimationFrame(id){frames.delete(id)},localStorage:{getItem(){throw Error('blocked storage')},setItem(){throw Error('blocked storage')}},alert(s){throw Error(s)},Math,Date};
 vm.createContext(c);vm.runInContext(fs.readFileSync('game.js','utf8')+'\nthis.audit={initializeGame,startGame,setPaused,keyDownHandler,keyUpHandler,runGameLoop,endGame,update,activateSmartBomb,get:()=>({paused,started,score,level,lives,smartBombs,keys:{...keys},lastFrameTime,gameOver}),setTime:v=>lastFrameTime=v};',c);c.audit.initializeGame();return {...c,events,windowEvents,elements,frames};}
test('starts with blocked local storage and the actual HTML controls',()=>{const c=setup();for(const id of ['score-display','lives-display','high-score-display','pause-overlay','pause-button','resume-button'])assert(c.elements.has(id),'Missing '+id);c.audit.startGame();assert(c.audit.get().started);assert.equal(c.audit.get().smartBombs,1);});
test('pause clears keys and stops updates; resume schedules only once',()=>{const c=setup();c.audit.startGame();c.audit.keyDownHandler({key:'ArrowUp',preventDefault(){}});c.audit.setPaused(true);const before=c.audit.get();assert.deepEqual(Object.keys(before.keys),[]);c.audit.runGameLoop(60000);assert.equal(c.audit.get().lastFrameTime,before.lastFrameTime);c.audit.setPaused(false);const count=c.frames.size;c.audit.setPaused(false);assert.equal(c.frames.size,count);assert.equal(c.audit.get().lastFrameTime,1000);});
test('P toggles once and losing visibility pauses',()=>{const c=setup();c.audit.startGame();c.audit.keyDownHandler({key:'p',repeat:false,preventDefault(){}});assert(c.audit.get().paused);c.audit.keyDownHandler({key:'p',repeat:true,preventDefault(){}});assert(c.audit.get().paused);c.audit.setPaused(false);c.document.hidden=true;c.events.visibilitychange();assert(c.audit.get().paused);});
test('smart bomb awards points and advances the visible level',()=>{const c=setup();c.audit.startGame();c.audit.activateSmartBomb();c.audit.update(0);assert.equal(c.audit.get().score,50);assert.equal(c.audit.get().level,2);assert(c.elements.get('score-display').textContent.includes('Level: 2'));c.audit.endGame();assert(c.audit.get().gameOver);});
test('word list is shipped, valid and matches guide; no dead mute control',()=>{const words=JSON.parse(fs.readFileSync('dictionary.json'));assert.equal(words.length,39);assert.equal(new Set(words).size,39);assert(words.every(w=>/^[A-Z]+$/.test(w)));assert(!fs.readFileSync('play.html','utf8').includes('mute-button'));assert(fs.readFileSync('index.html','utf8').includes('39-word'));});
test('a quick bomb tap works between animation frames',()=>{const c=setup();c.audit.startGame();c.audit.keyDownHandler({key:'b',repeat:false,preventDefault(){}});c.audit.keyUpHandler({key:'b'});assert.equal(c.audit.get().score,50);assert.equal(c.audit.get().smartBombs,0);});
test('space on a native button retains browser activation',()=>{const c=setup();c.audit.startGame();let prevented=false;c.audit.keyDownHandler({key:' ',target:{tagName:'BUTTON'},preventDefault(){prevented=true}});assert(!prevented);});

test("keyboard auto-repeat cannot spend a smart bomb",()=>{const c=setup();c.audit.startGame();c.audit.keyDownHandler({key:"b",repeat:true,preventDefault(){}});assert.equal(c.audit.get().smartBombs,1);assert.equal(c.audit.get().score,0);});
